# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/virgo/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/virgo

PRODUCT_COPY_FILES += \
    vendor/xiaomi/virgo/proprietary/vendor/lib/libsensors.leo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensors.leo.so \
    vendor/xiaomi/virgo/proprietary/vendor/lib/libinvensense_hal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libinvensense_hal.so
